Repository OpenTabletDriver/Plugin-Repository, pull requests merged in 2025-05, with the labels that each got.

#126 TiltCalibration: Move into subfolder
  Repository/0.6.4.0/Vineyo/TiltCalibration/TiltCalibration.json
Labels: bug, update

#127 Validate JSON directory paths
  validate.sh
Labels: enhancement

#128 Update TemporalResampler to v1.5.0
  Repository/0.6.4.0/shmkle/TemporalResampler/TemporalResampler.json
Labels: update
